// Country names for the data-SIM catalogue, keyed by ISO 3166 alpha-2 ("EU" = Europe-wide plans). Client-safe.

export const COUNTRIES: Record<string, { mn: string; en: string }> = {
  JP: { mn: "Япон", en: "Japan" },
  KR: { mn: "Солонгос", en: "South Korea" },
  CN: { mn: "Хятад", en: "China" },
  HK: { mn: "Хонконг", en: "Hong Kong" },
  MO: { mn: "Макао", en: "Macau" },
  TW: { mn: "Тайвань", en: "Taiwan" },
  SG: { mn: "Сингапур", en: "Singapore" },
  MY: { mn: "Малайз", en: "Malaysia" },
  TH: { mn: "Тайланд", en: "Thailand" },
  VN: { mn: "Вьетнам", en: "Vietnam" },
  PH: { mn: "Филиппин", en: "Philippines" },
  ID: { mn: "Индонез", en: "Indonesia" },
  KH: { mn: "Камбож", en: "Cambodia" },
  LA: { mn: "Лаос", en: "Laos" },
  MM: { mn: "Мьянмар", en: "Myanmar" },
  IN: { mn: "Энэтхэг", en: "India" },
  NP: { mn: "Балба", en: "Nepal" },
  LK: { mn: "Шри Ланка", en: "Sri Lanka" },
  MV: { mn: "Мальдив", en: "Maldives" },
  RU: { mn: "ОХУ", en: "Russia" },
  KZ: { mn: "Казахстан", en: "Kazakhstan" },
  KG: { mn: "Киргиз", en: "Kyrgyzstan" },
  UZ: { mn: "Узбекистан", en: "Uzbekistan" },
  GE: { mn: "Гүрж", en: "Georgia" },
  TR: { mn: "Турк", en: "Turkey" },
  AE: { mn: "АНЭУ", en: "UAE" },
  QA: { mn: "Катар", en: "Qatar" },
  SA: { mn: "Саудын Араб", en: "Saudi Arabia" },
  IL: { mn: "Израиль", en: "Israel" },
  EG: { mn: "Египет", en: "Egypt" },
  MA: { mn: "Марокко", en: "Morocco" },
  ZA: { mn: "Өмнөд Африк", en: "South Africa" },
  EU: { mn: "Европ", en: "Europe" },
  GB: { mn: "Их Британи", en: "United Kingdom" },
  DE: { mn: "Герман", en: "Germany" },
  FR: { mn: "Франц", en: "France" },
  IT: { mn: "Итали", en: "Italy" },
  ES: { mn: "Испани", en: "Spain" },
  PT: { mn: "Португал", en: "Portugal" },
  NL: { mn: "Нидерланд", en: "Netherlands" },
  BE: { mn: "Бельги", en: "Belgium" },
  CH: { mn: "Швейцари", en: "Switzerland" },
  AT: { mn: "Австри", en: "Austria" },
  CZ: { mn: "Чех", en: "Czechia" },
  PL: { mn: "Польш", en: "Poland" },
  HU: { mn: "Унгар", en: "Hungary" },
  GR: { mn: "Грек", en: "Greece" },
  SE: { mn: "Швед", en: "Sweden" },
  NO: { mn: "Норвеги", en: "Norway" },
  FI: { mn: "Финлянд", en: "Finland" },
  DK: { mn: "Дани", en: "Denmark" },
  US: { mn: "АНУ", en: "United States" },
  CA: { mn: "Канад", en: "Canada" },
  MX: { mn: "Мексик", en: "Mexico" },
  BR: { mn: "Бразил", en: "Brazil" },
  AR: { mn: "Аргентин", en: "Argentina" },
  AU: { mn: "Австрали", en: "Australia" },
  NZ: { mn: "Шинэ Зеланд", en: "New Zealand" },
};

export const countryName = (code: string, locale: "mn" | "en") => COUNTRIES[code]?.[locale] ?? code;
