// Starter content for the Mongolia map. Admins edit all of it in Admin → Монгол орон.
// Attractions are one per line; the English list is in the same order.

export type RegionSeed = {
  code: string;
  name: string;
  nameEn: string;
  center: string;
  centerEn: string;
  summary: string;
  summaryEn: string;
  history: string;
  historyEn: string;
  culture: string;
  cultureEn: string;
  attractions: string;
  attractionsEn: string;
};

const L = (...xs: string[]) => xs.join("\n");

export const REGION_SEED: RegionSeed[] = [
  {
    code: "ulaanbaatar", name: "Улаанбаатар", nameEn: "Ulaanbaatar", center: "Улаанбаатар", centerEn: "Ulaanbaatar",
    summary: "Монгол Улсын нийслэл, улс орны улс төр, соёл, эдийн засгийн төв.",
    summaryEn: "The capital and the political, cultural and economic heart of Mongolia.",
    history: "1639 онд Өргөө нэрээр нүүдлийн хийд-хот хэлбэрээр үүсэн байгуулагдаж, олон удаа нүүсний эцэст Туулын хөндийд суурьшсан. 1924 онд Улаанбаатар хэмээн нэрлэгдсэн.",
    historyEn: "Founded in 1639 as Örgöö, a mobile monastery town that moved many times before settling in the Tuul valley. It was renamed Ulaanbaatar in 1924.",
    culture: "Гандантэгчэнлин хийд, музей, театрууд төвлөрсөн; Наадмын баярын гол арга хэмжээ энд болдог.",
    cultureEn: "Home to Gandantegchenlin Monastery, the main museums and theatres, and the central Naadam festivities.",
    attractions: L("Гандантэгчэнлин хийд", "Чингис хааны талбай", "Богд хааны ордон музей", "Зайсан толгой", "Үндэсний түүхийн музей"),
    attractionsEn: L("Gandantegchenlin Monastery", "Chinggis Khaan Square", "Bogd Khan Palace Museum", "Zaisan Hill", "National Museum of Mongolia"),
  },
  {
    code: "tuv", name: "Төв", nameEn: "Töv", center: "Зуунмод", centerEn: "Zuunmod",
    summary: "Нийслэлийг тойрсон аймаг — өдрийн аялал, амралтын гол чиглэл.",
    summaryEn: "The province around the capital and the go-to area for day trips and weekend escapes.",
    history: "Богд хан уулын дархан цаазат газар нь дэлхийн хамгийн эртний хамгаалалттай газруудын нэг гэж тооцогддог. Маньжушрийн хийдийн туурь энд бий.",
    historyEn: "Bogd Khan Mountain is counted among the world's oldest protected areas, and the ruins of Manzushir Monastery lie on its slopes.",
    culture: "Малчин өрхөд зочлох, морь унах, гэр кемпэд хоноглох нь хамгийн түгээмэл.",
    cultureEn: "Visiting herder families, horse riding and staying in ger camps are the classic experiences here.",
    attractions: L("Горхи-Тэрэлжийн байгалийн цогцолборт газар", "Чингис хааны морьт хөшөө", "Хустайн байгалийн цогцолборт газар (тахь)", "Маньжушрийн хийдийн туурь", "Мэлхий хад"),
    attractionsEn: L("Gorkhi-Terelj National Park", "Chinggis Khaan Equestrian Statue", "Khustai National Park (Przewalski's horses)", "Manzushir Monastery ruins", "Turtle Rock"),
  },
  {
    code: "uvurkhangai", name: "Өвөрхангай", nameEn: "Övörkhangai", center: "Арвайхээр", centerEn: "Arvaikheer",
    summary: "Их Монгол Улсын нийслэл Хархорум оршиж байсан түүхийн өлгий нутаг.",
    summaryEn: "Cradle of Mongolian history and site of Karakorum, capital of the Mongol Empire.",
    history: "XIII зуунд Хархорум хот Их Монгол Улсын нийслэл байв. 1586 онд түүний ойролцоо Эрдэнэ Зуу хийд байгуулагдсан. Орхоны хөндийн соёлын дурсгалт газар ЮНЕСКО-гийн өвд бүртгэлтэй.",
    historyEn: "Karakorum was the capital of the Mongol Empire in the 13th century, and Erdene Zuu Monastery was founded beside it in 1586. The Orkhon Valley Cultural Landscape is a UNESCO World Heritage site.",
    culture: "Нүүдэлчдийн уламжлалт аж ахуй, Хангайн морин соёл хадгалагдан үлдсэн.",
    cultureEn: "Traditional herding life and the horse culture of the Khangai remain very much alive.",
    attractions: L("Эрдэнэ Зуу хийд", "Хархорум музей", "Орхоны хүрхрээ", "Төвхөн хийд", "Хужирт рашаан сувилал"),
    attractionsEn: L("Erdene Zuu Monastery", "Kharkhorum Museum", "Orkhon Waterfall", "Tövkhön Monastery", "Khujirt hot springs"),
  },
  {
    code: "arkhangai", name: "Архангай", nameEn: "Arkhangai", center: "Цэцэрлэг", centerEn: "Tsetserleg",
    summary: "Ногоон хангай, галт уулын тогоо, халуун рашаанаараа алдартай.",
    summaryEn: "Green Khangai valleys, volcanic craters and hot springs.",
    history: "Хөшөө Цайдамын Түрэгийн үеийн бичээс, хиргисүүр, буган хөшөө олноор бий нь эртний нүүдэлчдийн төв байсныг гэрчилнэ.",
    historyEn: "Turkic-era inscriptions at Khöshöö Tsaidam, burial mounds and deer stones show it was a centre of early nomadic empires.",
    culture: "Айраг, цагаан идээгээрээ алдартай малчны нутаг.",
    cultureEn: "Herding country famous for airag (fermented mare's milk) and dairy foods.",
    attractions: L("Тэрхийн Цагаан нуур", "Хорго уулын тогоо", "Цэнхэрийн халуун рашаан", "Тайхар чулуу", "Зая гэгээний хүрээ музей"),
    attractionsEn: L("Terkhiin Tsagaan Lake", "Khorgo volcano crater", "Tsenkher hot springs", "Taikhar Rock", "Zayain Gegeenii Khüree Museum"),
  },
  {
    code: "khuvsgul", name: "Хөвсгөл", nameEn: "Khövsgöl", center: "Мөрөн", centerEn: "Mörön",
    summary: "\"Монголын цэнхэр сувд\" Хөвсгөл нуур, тайгын цаатан иргэдийн нутаг.",
    summaryEn: "Home of Lake Khövsgöl, the \"Blue Pearl of Mongolia\", and the reindeer-herding Tsaatan.",
    history: "Үшкийн өвөрийн буган хөшөөний цогцолбор нь хүрэл зэвсгийн үеийн хамгийн алдартай дурсгалуудын нэг.",
    historyEn: "The Uushigiin Övör deer-stone complex is one of the best-known Bronze Age monuments in the country.",
    culture: "Цаатан (духа) иргэд цаа буга маллах уламжлалаа хадгалж байна; бөөгийн шүтлэг хүчтэй.",
    cultureEn: "The Tsaatan (Dukha) still herd reindeer in the taiga, and shamanic traditions remain strong.",
    attractions: L("Хөвсгөл нуур", "Хатгал тосгон", "Үшкийн өвөрийн буган хөшөө", "Цаатны тайга", "Дархадын хотгор"),
    attractionsEn: L("Lake Khövsgöl", "Khatgal village", "Uushigiin Övör deer stones", "Tsaatan reindeer taiga", "Darkhad Depression"),
  },
  {
    code: "umnugovi", name: "Өмнөговь", nameEn: "Ömnögovi", center: "Даланзадгад", centerEn: "Dalanzadgad",
    summary: "Говийн гайхамшиг — элсэн манхан, мөсөн хавцал, үлэг гүрвэлийн олдвор.",
    summaryEn: "The Gobi at its most dramatic: dunes, an ice-filled gorge and dinosaur fossils.",
    history: "1920-иод онд Баянзагаас үлэг гүрвэлийн өндөг дэлхийд анх олдсоноор палеонтологийн төв болсон.",
    historyEn: "Dinosaur eggs found at Bayanzag in the 1920s made the region a centre of palaeontology.",
    culture: "Тэмээ маллагаа, говийн малчдын ахуй; Тэмээн баяр зохиогддог.",
    cultureEn: "Camel herding and Gobi nomadic life; camel festivals are held here.",
    attractions: L("Хонгорын элс", "Ёлын ам", "Баянзаг (Улаан эрэг)", "Говь гурван сайхан байгалийн цогцолборт газар", "Хэрмэн цав"),
    attractionsEn: L("Khongoryn Els dunes", "Yolyn Am gorge", "Bayanzag (Flaming Cliffs)", "Gobi Gurvansaikhan National Park", "Khermen Tsav canyon"),
  },
  {
    code: "khentii", name: "Хэнтий", nameEn: "Khentii", center: "Чингис хот", centerEn: "Chinggis city",
    summary: "Чингис хааны мэндэлсэн, өссөн нутаг.",
    summaryEn: "The land where Chinggis Khaan was born and grew up.",
    history: "Дэлүүн болдог нь Чингис хааны мэндэлсэн газар гэж үздэг. Хөх нуурт Тэмүжин хаан ширээнд өргөмжлөгдсөн гэдэг.",
    historyEn: "Deluun Boldog is traditionally held to be Chinggis Khaan's birthplace, and Khökh Lake the place Temüjin was proclaimed khan.",
    culture: "Их эзэний түүхтэй холбоотой олон дурсгалт газар, домог яриа хадгалагдсан.",
    cultureEn: "Many sites and legends tied to the Great Khan's life are preserved here.",
    attractions: L("Дэлүүн болдог", "Хөх нуур", "Балдан Бэрээвэн хийд", "Хэрлэн мөрөн"),
    attractionsEn: L("Deluun Boldog", "Khökh Lake", "Baldan Bereeven Monastery", "Kherlen River"),
  },
  {
    code: "bayan-ulgii", name: "Баян-Өлгий", nameEn: "Bayan-Ölgii", center: "Өлгий", centerEn: "Ölgii",
    summary: "Алтайн өндөрлөг, казах бүргэдчдийн нутаг.",
    summaryEn: "High Altai mountains and the land of the Kazakh eagle hunters.",
    history: "Цагаан салаа – Бага Ойгорын хадны зураг ЮНЕСКО-гийн өвд бүртгэгдсэн (Монгол Алтайн хадны зургийн цогцолбор).",
    historyEn: "The rock art of Tsagaan Salaa and Baga Oigor is part of the UNESCO-listed Petroglyphic Complexes of the Mongolian Altai.",
    culture: "Казах үндэстний хэл, ёс заншил, бүргэдээр ан хийх уламжлал; Бүргэдийн баяр намар болдог.",
    cultureEn: "Kazakh language and customs and the tradition of hunting with golden eagles; the Eagle Festival is held each autumn.",
    attractions: L("Алтай Таван Богд байгалийн цогцолборт газар", "Хүйтэн оргил", "Бүргэдийн баяр", "Цагаан салаа – Бага Ойгорын хадны зураг", "Толбо нуур"),
    attractionsEn: L("Altai Tavan Bogd National Park", "Khüiten Peak", "Golden Eagle Festival", "Tsagaan Salaa & Baga Oigor rock art", "Tolbo Lake"),
  },
  {
    code: "uvs", name: "Увс", nameEn: "Uvs", center: "Улаангом", centerEn: "Ulaangom",
    summary: "Монголын хамгийн том нуур — Увс нуур ба олон төрлийн ландшафт.",
    summaryEn: "Mongolia's largest lake and a mosaic of landscapes.",
    history: "Увс нуурын хотгор ЮНЕСКО-гийн Дэлхийн өвд бүртгэлтэй; мянга мянган эртний булш, хадны зураг бий.",
    historyEn: "The Uvs Nuur Basin is a UNESCO World Heritage site with thousands of ancient burials and petroglyphs.",
    culture: "Дөрвөд, хотон, баяд зэрэг ястнууд амьдардаг, баруун монголын ёс заншил хадгалагдсан.",
    cultureEn: "Home to Dörvöd, Khoton and Bayad peoples and distinct western Mongolian customs.",
    attractions: L("Увс нуур", "Хархираа, Түргэн уул", "Алтан элс", "Үүрэг нуур"),
    attractionsEn: L("Uvs Lake", "Kharkhiraa and Türgen mountains", "Altan Els dunes", "Üüreg Lake"),
  },
  {
    code: "khovd", name: "Ховд", nameEn: "Khovd", center: "Ховд", centerEn: "Khovd",
    summary: "Олон ястны соёл, нуур, Алтайн уулсын нутаг.",
    summaryEn: "A meeting point of many ethnic groups, great lakes and the Altai.",
    history: "Ховд хот XVIII зуунд Манжийн цэргийн бэхлэлт болж байгуулагдсан. Цэнхэрийн агуйн хадны зураг эртний хүмүүсийн амьдралыг харуулна.",
    historyEn: "Khovd city began as an 18th-century Manchu garrison, and the Tsenkher Cave paintings record prehistoric life.",
    culture: "Захчин, торгууд, өөлд, урианхай зэрэг 10 гаруй ястан амьдардаг; тууль, хөөмийн уламжлалтай.",
    cultureEn: "More than ten ethnic groups, including Zakhchin, Torguud, Ööld and Uriankhai; a home of epic song and khöömii throat singing.",
    attractions: L("Хар-Ус нуур", "Цэнхэрийн агуй", "Мөнххайрхан уул", "Ховд хотын Сангийн хэрэм"),
    attractionsEn: L("Khar-Us Lake", "Tsenkher Cave", "Mönkhkhairkhan Mountain", "Sangiin Kherem fortress in Khovd"),
  },
  {
    code: "zavkhan", name: "Завхан", nameEn: "Zavkhan", center: "Улиастай", centerEn: "Uliastai",
    summary: "Отгонтэнгэр уул, элсэн манхантай нуурууд.",
    summaryEn: "Sacred Otgontenger mountain and lakes framed by dunes.",
    history: "Улиастай хот XVIII зуунаас Манжийн жанжны сууц байсан, түүхэн хэрэм, барилгууд үлдсэн.",
    historyEn: "From the 18th century Uliastai was the seat of the Manchu military governor, and historic walls and buildings remain.",
    culture: "Отгонтэнгэр уулыг төрийн тахилгат уул болгон тахидаг.",
    cultureEn: "Otgontenger is worshipped as a state-sacred mountain.",
    attractions: L("Отгонтэнгэр уул", "Хар нуур", "Улиастай хот"),
    attractionsEn: L("Otgontenger Mountain", "Khar Lake", "Uliastai town"),
  },
  {
    code: "govi-altai", name: "Говь-Алтай", nameEn: "Govi-Altai", center: "Алтай", centerEn: "Altai",
    summary: "Говь, Алтайн нуруу нийлсэн зэрлэг байгалийн нутаг.",
    summaryEn: "Wild country where the Gobi meets the Altai range.",
    history: "Эртний хадны зураг, хүн чулуу олноор хадгалагдсан.",
    historyEn: "Rich in ancient petroglyphs and stone figures.",
    culture: "Говийн малчдын ахуй, хавтгай (зэрлэг тэмээ) хамгаалах ажил.",
    cultureEn: "Gobi herding life and conservation of the wild Bactrian camel.",
    attractions: L("Эж хайрхан уул", "Их говийн дархан цаазат газар", "Сутай хайрхан", "Шаргын говь"),
    attractionsEn: L("Eej Khairkhan Mountain", "Great Gobi Strictly Protected Area", "Sutai Khairkhan", "Shargyn Gobi"),
  },
  {
    code: "bayankhongor", name: "Баянхонгор", nameEn: "Bayankhongor", center: "Баянхонгор", centerEn: "Bayankhongor",
    summary: "Хангайн нуруунаас говь хүртэл үргэлжилсэн олон янзын байгаль.",
    summaryEn: "Landscapes stretching from the Khangai mountains down to the Gobi.",
    history: "Бичигтийн амны хадны зураг, үлэг гүрвэлийн олдворууд олддог.",
    historyEn: "Known for the Bichigtiin Am rock art and dinosaur finds.",
    culture: "Хангай, говийн малчдын ахуй нэг аймагт зэрэгцэн оршдог.",
    cultureEn: "Khangai and Gobi herding traditions side by side in one province.",
    attractions: L("Орог нуур", "Их Богд уул", "Бичигтийн амны хадны зураг", "Шаргалжуутын рашаан"),
    attractionsEn: L("Orog Lake", "Ikh Bogd Mountain", "Bichigtiin Am rock art", "Shargaljuut hot springs"),
  },
  {
    code: "dundgovi", name: "Дундговь", nameEn: "Dundgovi", center: "Мандалговь", centerEn: "Mandalgovi",
    summary: "Нийслэлд ойр говийн гоо үзэсгэлэн — хадан хясаа, тал.",
    summaryEn: "Gobi scenery within reach of the capital: rock formations and open steppe.",
    history: "Цагаан суварга нь эртний тэнгисийн ёроолын давхаргуудыг ил харуулдаг.",
    historyEn: "Tsagaan Suvarga exposes the layers of an ancient sea floor.",
    culture: "Говийн малчид, Бага газрын чулуун дахь хийдийн туурь.",
    cultureEn: "Gobi herders and monastery ruins among the Baga Gazriin Chuluu rocks.",
    attractions: L("Цагаан суварга", "Бага газрын чулуу", "Их газрын чулуу", "Сүм хөх бурдын туурь"),
    attractionsEn: L("Tsagaan Suvarga", "Baga Gazriin Chuluu", "Ikh Gazriin Chuluu", "Süm Khökh Burd ruins"),
  },
  {
    code: "dornogovi", name: "Дорноговь", nameEn: "Dornogovi", center: "Сайншанд", centerEn: "Sainshand",
    summary: "Энергийн төв гэгддэг Шамбалын орон, Замын-Үүдийн хил.",
    summaryEn: "The \"energy centre\" of Shambhala and the Zamyn-Üüd border crossing.",
    history: "XIX зууны Догшин ноён хутагт Данзанравжаа Хамарын хийдийг байгуулж, анхны мэргэжлийн театрыг үүсгэсэн.",
    historyEn: "In the 19th century the Noyon Khutagt Danzanravjaa founded Khamaryn Khiid and staged some of Mongolia's first theatre.",
    culture: "Данзанравжаагийн уран бүтээл, говийн сүсэг бишрэлийн уламжлал.",
    cultureEn: "Danzanravjaa's poetry and plays and a strong tradition of Gobi pilgrimage.",
    attractions: L("Хамарын хийд ба Шамбалын орон", "Данзанравжаагийн музей", "Улаан суварга", "Зүүн Сайхан"),
    attractionsEn: L("Khamaryn Khiid and Shambhala site", "Danzanravjaa Museum", "Ulaan Suvarga", "Züün Saikhan"),
  },
  {
    code: "govisumber", name: "Говьсүмбэр", nameEn: "Govisümber", center: "Чойр", centerEn: "Choir",
    summary: "Төмөр замын дагуух жижиг аймаг, говь, хээрийн заагт.",
    summaryEn: "A small province on the railway, where steppe meets Gobi.",
    history: "Чойр хот Трансмонголын төмөр замын буудал болж хөгжсөн.",
    historyEn: "Choir grew up as a station on the Trans-Mongolian Railway.",
    culture: "Хээрийн малчдын уламжлалт ахуй.",
    cultureEn: "Traditional steppe herding life.",
    attractions: L("Чойрын Богд уул", "Чойр хот"),
    attractionsEn: L("Choiriin Bogd Mountain", "Choir town"),
  },
  {
    code: "dornod", name: "Дорнод", nameEn: "Dornod", center: "Чойбалсан", centerEn: "Choibalsan",
    summary: "Зүүн Монголын өргөн тал, зээрийн сүрэг, Халх голын түүх.",
    summaryEn: "The vast eastern steppe, gazelle herds and the history of Khalkhin Gol.",
    history: "1939 оны Халх голын тулалдааны дурсгалт газрууд, Чингисийн далангийн туурь оршдог.",
    historyEn: "Memorials of the 1939 Battle of Khalkhin Gol and remains of the Chinggis Wall are found here.",
    culture: "Буриад, халх, баргын уламжлал; тал хээрийн амьдрал.",
    cultureEn: "Buryat, Khalkh and Barga traditions and life on the open steppe.",
    attractions: L("Халх голын дурсгалт газар", "Буйр нуур", "Монгол дагуурын дархан цаазат газар", "Чойбалсан хот"),
    attractionsEn: L("Khalkhin Gol memorial sites", "Buir Lake", "Mongol Daguur Strictly Protected Area", "Choibalsan city"),
  },
  {
    code: "sukhbaatar", name: "Сүхбаатар", nameEn: "Sükhbaatar", center: "Баруун-Урт", centerEn: "Baruun-Urt",
    summary: "Дарьгангын унтарсан галт уулс, Ганга нуур.",
    summaryEn: "Dariganga's extinct volcanoes and Ganga Lake.",
    history: "Дарьгангын нутагт олон зуун хүн чулуу, эртний дурсгал бий.",
    historyEn: "The Dariganga area holds hundreds of stone figures and ancient monuments.",
    culture: "Дарьганга ястны мөнгөн дарханы урлаг алдартай.",
    cultureEn: "Dariganga silversmithing is renowned.",
    attractions: L("Шилийн Богд уул", "Ганга нуур", "Молцог элс", "Дарьгангын хүн чулуу"),
    attractionsEn: L("Shiliin Bogd Mountain", "Ganga Lake", "Moltsog Els dunes", "Dariganga stone figures"),
  },
  {
    code: "selenge", name: "Сэлэнгэ", nameEn: "Selenge", center: "Сүхбаатар", centerEn: "Sükhbaatar",
    summary: "Тариалан, ой мод, томоохон голуудын нутаг.",
    summaryEn: "Farmland, forests and great rivers.",
    history: "XVIII зууны Амарбаясгалант хийд нь Монголын хамгийн бүрэн хадгалагдсан хийдийн цогцолборуудын нэг.",
    historyEn: "18th-century Amarbayasgalant Monastery is one of the best-preserved monastery complexes in Mongolia.",
    culture: "Тариаланчдын уламжлал, Орос хил дагуух худалдааны түүх.",
    cultureEn: "Farming traditions and a long history of trade along the Russian border.",
    attractions: L("Амарбаясгалант хийд", "Сэлэнгэ мөрөн"),
    attractionsEn: L("Amarbayasgalant Monastery", "Selenge River"),
  },
  {
    code: "bulgan", name: "Булган", nameEn: "Bulgan", center: "Булган", centerEn: "Bulgan",
    summary: "Ой, тал хосолсон, галт уулын тогоотой нутаг.",
    summaryEn: "Forest and steppe with volcanic craters.",
    history: "Уйгурын эзэнт гүрний үеийн дурсгалууд олддог.",
    historyEn: "Remains from the Uyghur Khaganate are found here.",
    culture: "Хангайн малчдын уламжлал, айргийн соёл.",
    cultureEn: "Khangai herding traditions and airag culture.",
    attractions: L("Уран-Тогоо Тулга уулын байгалийн дурсгалт газар", "Хөгнө хан уул", "Эрдэнэт хотын ойролцоох ой"),
    attractionsEn: L("Uran-Togoo Tulga volcanoes", "Khögnö Khan Mountain", "Forests around Erdenet"),
  },
  {
    code: "orkhon", name: "Орхон", nameEn: "Orkhon", center: "Эрдэнэт", centerEn: "Erdenet",
    summary: "Уул уурхайн хот Эрдэнэт бүхий жижиг аймаг.",
    summaryEn: "A small province built around the mining city of Erdenet.",
    history: "Эрдэнэт хот 1970-аад онд зэсийн уурхайн хамт байгуулагдсан.",
    historyEn: "Erdenet was founded in the 1970s together with its copper mine.",
    culture: "Орчин үеийн хотын амьдрал, ойр орчмын малчны нутаг.",
    cultureEn: "Modern city life surrounded by herding country.",
    attractions: L("Эрдэнэт хот", "Эрдэнэтийн уурхайн үзэх цэг"),
    attractionsEn: L("Erdenet city", "Erdenet mine viewpoint"),
  },
  {
    code: "darkhan-uul", name: "Дархан-Уул", nameEn: "Darkhan-Uul", center: "Дархан", centerEn: "Darkhan",
    summary: "Монголын гурав дахь том хот Дархан бүхий аймаг.",
    summaryEn: "Home to Darkhan, Mongolia's third-largest city.",
    history: "Дархан хот 1961 онд аж үйлдвэрийн төв болгон байгуулагдсан.",
    historyEn: "Darkhan was founded in 1961 as an industrial centre.",
    culture: "Хотын соёл, хойд зүгийн гол замын дагуух суурин.",
    cultureEn: "Urban culture on the main route north.",
    attractions: L("Дархан хот", "Шарын гол"),
    attractionsEn: L("Darkhan city", "Sharyn Gol"),
  },
];
